### ISSUE TITLE
Single Test Runner Feature

### ISSUE THREAD

**Issue by nesatuf** [aaltat/robotframework-from-sublime#48]
It will be so handy to have a single test runner. 
Like we have in PyCharm IDE.
http://blog.bigbinary.com/2015/10/11/configuring-pycharm-to-run-tests.html

**Comment by aaltat** [comment]
In Sublime, there is a [build system](http://docs.sublimetext.info/en/latest/reference/build_systems.html) which could be used to do something similar. Although I am not fan of that kind setups, I do see the benefits of having such a feature. There are bunch of issues, like #18, #35 and so, which are more important than this one and therefore I don't have time to implement it right now. But I am happy to receive a pull request for the implementation.

**Comment by aaltat** [comment]
I did play around the build system and it was easy to do. The commit https://github.com/aaltat/robotframework-from-sublime/commit/80f44bffc907d6eb293c4c967e431bce88ef8e87 contains initial version. By default `Ctrl + b` runs the default build, which runs `pybot /path/to/open/file.robot`. You can configure the system in similar way as in the PyCharm by editing the RobotFrameworkDataEditor.sublime-build file and selecting the proper build system by pressing `Ctrl + Shift + b`. Now the built system is platform specific, Windows, but that user can change to suite their need. 

Could you try out the feature and provide some feedback.

**Comment by aaltat** [comment]
And https://github.com/aaltat/robotframework-from-sublime/commit/fdd7eaba40c9eb87f798b1946f7e6c9dff7a47c0 provides a menu item to edit build configuration.

**Comment by aaltat** [comment]
The https://github.com/aaltat/robotframework-from-sublime/commit/107f4efb7792a108ceea49dc674df54819efd7f3 makes the build system run on any OS. Need to write documentation how to configure/use the build system if @nesatuf is happy too we can close the issue.

**Comment by nesatuf** [comment]
Appreciate @aaltat
Can't wait to see the completed package in the Package Central.

**Comment by aaltat** [comment]
You can actually use the plugin already from GitHub. Instructions in here: https://github.com/andriyko/sublime-robot-framework-assistant/wiki/Installation-guide-for-pre-release

**Comment by aaltat** [comment]
This is documented in the https://github.com/andriyko/sublime-robot-framework-assistant/wiki/Running-test-suite-from-Sublime-Text. Closing
