### ISSUE TITLE
Possibility to change argument formating

### ISSUE THREAD

**Issue by huuhtaneno** [aaltat/robotframework-from-sublime#52]
I think the plugin should give you the possibility to change the argument formating from:
Keyword
...    arg1
...    arg2

I would like by default to have the arguments following the keyword as follows:
Keyword    arg1    arg2

**Comment by aaltat** [comment]
Moved to: https://github.com/andriyko/sublime-robot-framework-assistant/issues/53

**Comment by aaltat** [comment]
This is now possible, please get the plugin from https://github.com/andriyko/sublime-robot-framework-assistant/tree/rewrite_to_version_2
